### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by nuanfeng1yue** [Zhao-sai-sai/Full-Scanner#2]
ERROR: Could not find a version that satisfies the requirement ftplib (from versions: none)
ERROR: No matching distribution found for ftplib

换源，更新pip都试过了。

**Comment by CuriousLearnerDev** [comment]
这个库之前好像需要安装现在好像已经有了不需要安装了，不安装这个库也可以，你可以手动删除requirements.txt文件里面的ftplib

**Comment by nuanfeng1yue** [comment]
Traceback (most recent call last):
  File "D:\fox下载\Full-Scanner-master\Full-Scanner.py", line 28, in <module>
    judge.GUI(args.GUI)  # GUI
  File "D:\fox下载\Full-Scanner-master\judge.py", line 18, in GUI
    from lib.GUI import cs
  File "D:\fox下载\Full-Scanner-master\lib\GUI\cs.py", line 15, in <module>
    from lib.GUI import Coding_tools
  File "D:\fox下载\Full-Scanner-master\lib\GUI\Coding_tools.py", line 325
    text='Base64
                ^
SyntaxError: EOL while scanning string literal

-GUI出现这个报错是啥问题

**Comment by CuriousLearnerDev** [comment]
已启动图形化的都这样吗，还是在使用过程中遇见的问题

**Comment by nuanfeng1yue** [comment]
启动图形化就会这样

**Comment by nuanfeng1yue** [comment]
linux没问题,windows会出现这个报错

**Comment by CuriousLearnerDev** [comment]
> 追溯（最近一次调用最后一次）：
文件“D:\fox下载\Full-Scanner-master\Full-Scanner.py”，第28行，in
judge.GUI(args.GUI) # GUI
File "D:\fox下载\Full-Scanner-master\judge.py"，第 18 行，在 GUI
从 lib.GUI 导入 cs
文件“D:\fox 下载\Full-Scanner-master\lib\GUI\cs.py”，第 15 行，在
从 lib.GUI 导入 Coding_tools
文件“D:\fox 下载\Full-Scanner-master\lib\GUI\Coding_tools.py”，第 325 行
text='Base64
^
SyntaxError: EOL while scanning string literal
-GUI出现这个报错是啥问题
> 启动图形化就会这样
> linux没有问题,windows会出现这个报错

打开`lib/GUI/cs.py`文件注释掉第11行的`sys.path.append("../../") # 解决上级库文件`这个给注释掉试试

![image](https://user-images.githubusercontent.com/72000175/232956284-8cd02404-2ccf-421a-be5c-8c4cec06c121.png)

还是不行，换一下其他的windows环境还是这样吗，或者是重新在git下载我这个前几天更新的版本

**Comment by nuanfeng1yue** [comment]
没问题了，感谢师傅
